# Start from ROS base image
FROM ros:noetic-ros-core

# Make a catkin workspace
WORKDIR /
RUN mkdir -p /catkin_ws/src
WORKDIR /catkin_ws/src

# Install Git, Python, and other dependencies
RUN apt-get update && \
    apt-get install -y git python3 python3-pip ros-noetic-rosbridge-server ros-noetic-tf2-web-republisher && \
    rm -rf /var/lib/apt/lists/*

# Additional dependencies for raspicam_node
RUN apt-get update && apt-get install -y ros-noetic-compressed-image-transport ros-noetic-camera-info-manager

RUN apt-get update && apt-get install -y ros-noetic-joy ros-noetic-teleop-twist-joy ros-noetic-teleop-twist-keyboard ros-noetic-amcl ros-noetic-map-server ros-noetic-move-base ros-noetic-urdf ros-noetic-xacro ros-noetic-rqt-image-view ros-noetic-gmapping ros-noetic-navigation ros-noetic-joint-state-publisher ros-noetic-robot-state-publisher ros-noetic-slam-gmapping ros-noetic-dwa-local-planner ros-noetic-joint-state-publisher-gui

RUN apt-get update && apt-get install -y ros-noetic-cartographer-ros
# Clone your ROS packages
RUN git clone -b noetic https://github.com/rigbetellabs/tortoisebot.git

RUN apt-get install -y ros-noetic-diagnostic-updater

WORKDIR /catkin_ws

# Build your ROS packages
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash; cd /catkin_ws; catkin_make"

# Source the workspace every time a new shell is opened in the container
RUN echo source /catkin_ws/devel/setup.bash >> ~/.bashrc

# Set the entry point to start a bash shell
CMD /bin/bash -c "source /catkin_ws/devel/setup.bash; roslaunch tortoisebot_slam tortoisebot_slam.launch"