version: '2'

services:
  ros-master:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    restart: always
    network_mode: host
    tty: true
    ipc: host
    environment:
      - ROS_HOSTNAME=master
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on

  firmware:
    image: therealnavzz/naveen-cp22:tortoisebot-ros1-real
    container_name: tortoisebot-ros1-real_final_2
    depends_on:
      - ros-master
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on
    restart: always
    network_mode: host
    tty: true
    ipc: host
    devices:
      - "/dev/ttyUSB0"
    cap_add:
      - SYS_RAWIO
    privileged: true

  slam:
    image: therealnavzz/naveen-cp22:tortoisebot-ros1-slam-real
    container_name: tortoisebot-ros1-real-slam_final_2
    depends_on:
      - ros-master
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on
    restart: always
    network_mode: host
    tty: true
    ipc: host
    privileged: true

  rviz:
    image: therealnavzz/naveen-cp22:tortoisebot-ros1-real-rviz
    container_name: tortoisebot-ros1-real-rviz_final_2
    depends_on:
      - ros-master
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
    network_mode: host
    tty: true
    ipc: host
    privileged: true
