# Start from ROS base image
FROM therealnavzz/misc:ros2-real

WORKDIR /ros2_ws

RUN /bin/bash -c "source install/setup.bash; colcon build"

RUN apt-get update && apt-get install -y ros-galactic-rviz2

RUN echo source /ros2_ws/install/setup.bash >> ~/.bashrc

CMD /bin/bash -c "source /ros2_ws/install/setup.bash; ros2 launch tortoisebot_slam cartographer.launch.py use_sim_time:=False"